import re
import logging
from typing import List, Dict, Any

logger = logging.getLogger(__name__)

class CitationService:
    def __init__(self):
        # Regex to find parenthetical source citations like (Source: DBMS Notes - Page 12)
        # Matches: (Source: <filename/subject> - Page <number>)
        self.citation_pattern = re.compile(r"\(Source:\s*(.*?)\s*-\s*Page\s*(\d+)\)", re.IGNORECASE)

    def _normalize(self, text: str) -> str:
        """Helper to normalize text for fuzzy matching (lowercase and alphanumeric only)"""
        return re.sub(r"[^\w]", "", text.lower())

    def citation_engine(self, answer: str, retrieved_chunks: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """
        Parses inline citations from the generated answer and cross-references them
        with the retrieved context chunks to verify their validity.
        
        Args:
            answer (str): The answer text generated by the LLM.
            retrieved_chunks (List[Dict[str, Any]]): Chunks retrieved from Pinecone.
            
        Returns:
            List[Dict[str, Any]]: List of verified citation objects actually referenced.
        """
        logger.info("Running citation engine verification...")
        
        # Find all citation matches in the text
        citations_found = self.citation_pattern.findall(answer)
        if not citations_found:
            logger.info("No parenthetical inline citations found in the text.")
            return []
            
        verified_citations = []
        seen_keys = set() # Avoid duplicate verified citations
        
        for extracted_source, extracted_page_str in citations_found:
            try:
                extracted_page = int(extracted_page_str)
            except ValueError:
                continue
                
            norm_extracted = self._normalize(extracted_source)
            matched_chunk = None
            
            # Cross-reference with retrieved chunks
            for chunk in retrieved_chunks:
                meta = chunk.get("metadata", {})
                filename = meta.get("filename", "")
                subject = meta.get("subject", "")
                page = meta.get("page", 0)
                
                # Check for exact page match and fuzzy source name match
                if int(page) == extracted_page:
                    norm_filename = self._normalize(filename)
                    norm_subject = self._normalize(subject)
                    
                    # Match if extracted source name is similar to filename or subject
                    if (norm_extracted in norm_filename) or (norm_filename in norm_extracted) or \
                       (norm_extracted in norm_subject) or (norm_subject in norm_extracted):
                        matched_chunk = chunk
                        break
            
            if matched_chunk:
                meta = matched_chunk["metadata"]
                cit_key = (meta.get("filename"), meta.get("page"))
                
                if cit_key not in seen_keys:
                    seen_keys.add(cit_key)
                    verified_citations.append({
                        "filename": meta.get("filename"),
                        "subject": meta.get("subject"),
                        "page": meta.get("page"),
                        "source": meta.get("source"),
                        "chunk_id": matched_chunk.get("chunk_id"),
                        "score": matched_chunk.get("score"),
                        "text": matched_chunk.get("text", "")
                    })
                    logger.info(f"Verified Citation: {meta.get('filename')} (Page {meta.get('page')})")
            else:
                logger.warning(f"Unverified/Hallucinated Citation: '{extracted_source}' on page {extracted_page}")
                
        return verified_citations
